// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {serial} from '../models';
import {uuid} from '../models';

export function GetSerialPort():Promise<Array<string>>;

export function SelectMonitor(arg1:string,arg2:serial.Mode):Promise<void>;

export function TestReult():Promise<void>;

export function UnselectMonitor(arg1:uuid.UUID):Promise<void>;
