// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMonitors() {
  return window['go']['main']['App']['GetMonitors']();
}

export function GetSerialPort() {
  return window['go']['main']['App']['GetSerialPort']();
}

export function SelectMonitor(arg1) {
  return window['go']['main']['App']['SelectMonitor'](arg1);
}

export function TestReult() {
  return window['go']['main']['App']['TestReult']();
}

export function UnselectMonitor(arg1) {
  return window['go']['main']['App']['UnselectMonitor'](arg1);
}
