// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['Config']['GetConfig']();
}

export function SetDepartment(arg1) {
  return window['go']['main']['Config']['SetDepartment'](arg1);
}

export function SetName(arg1) {
  return window['go']['main']['Config']['SetName'](arg1);
}
