// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<main.Config>;

export function SetDepartment(arg1:string):Promise<main.Config>;

export function SetName(arg1:string):Promise<main.Config>;
