// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportToExcel() {
  return window['go']['main']['Exporter']['ExportToExcel']();
}

export function SetContext(arg1) {
  return window['go']['main']['Exporter']['SetContext'](arg1);
}
