// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['main']['MeasurementService']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['main']['MeasurementService']['Delete'](arg1);
}

export function FindAll(arg1) {
  return window['go']['main']['MeasurementService']['FindAll'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['main']['MeasurementService']['Update'](arg1, arg2);
}

export function UpdatePatienID(arg1, arg2) {
  return window['go']['main']['MeasurementService']['UpdatePatienID'](arg1, arg2);
}
